steps:
  - label: ":runner: Dynamically launch Pipelines"
    plugins:
      - staticfloat/forerunner:
          # This will create one job per project
          watch:
            - tutorials/**/*.jmd
            - tutorials/**/*.toml
          path_processor: .buildkite/path_processors/project-coalescing
          target: .buildkite/run_tutorial.yml
          target_type: template
    agents:
      queue: "juliacpu"
      fastcpu: true
    if: build.message !~ /\[skip ci\]/