name: Add Navbar

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:  # Allows manual triggering

jobs:
  add-navbar:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the token has write permissions

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4  # Check out the gh-pages branch

      - name: Download insert_navbar.sh
        run: |
          curl -O https://raw.githubusercontent.com/shravanngoswamii/experimental/main/test/insert_navbar.sh
          chmod +x insert_navbar.sh

      - name: Update Navbar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the provided GITHUB_TOKEN
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          
          # Update all HTML files in the current directory (gh-pages root)
          ./insert_navbar.sh .
          
          # Check if there are any changes
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "added navbar"
            git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" gh-pages
          else
            echo "No changes to commit"
