name: Add Navbar

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-navbar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Download insert_navbar.sh
        run: |
          curl -O https://raw.githubusercontent.com/shravanngoswamii/experimental/main/test/insert_navbar.sh
          chmod +x insert_navbar.sh

      - name: Update Navbar
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          # Update all HTML files in the current directory (gh-pages root)
          ./insert_navbar.sh .
          
          # Check if there are any changes
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "add navbar"
            git push origin gh-pages
          else
            echo "No changes to commit"
          fi