name: Add Navbar
on:
  workflow_run:
    workflows: ["*"]
    types:
      - completed
  workflow_dispatch:

jobs:
  add-navbar:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0
      
      - name: Download insert_navbar.sh
        run: |
          curl -O https://raw.githubusercontent.com/shravanngoswamii/experimental/main/test/insert_navbar.sh
          chmod +x insert_navbar.sh
      
      - name: Update Navbar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash -e << EOF
          #!/bin/bash
          set -e
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          ./insert_navbar.sh .
          
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Updated navbar"
            git push "https://\${GITHUB_ACTOR}:\${GITHUB_TOKEN}@github.com/\${GITHUB_REPOSITORY}.git" gh-pages
          else
            echo "No changes to commit"
          fi
          EOF