name: Add Navbar

on:
  workflow_run:
    workflows: ["Initial"]  # add workflow names that generate docs in this list like `workflows: ["Docs Workflow", "Previews Workflow]`
    types:
      - completed
  workflow_dispatch:  # Allows manual triggering

jobs:
  add-navbar:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Update Navbar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e

          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

          # Download and execute the insert_navbar.sh script
          curl -s https://raw.githubusercontent.com/shravanngoswamii/experimental/main/test/insert_navbar.sh | bash -s .

          # Check if there are any changes
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "added navbar"
            git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" gh-pages
          else
            echo "No changes to commit"