name: 'BibTex Tidy'

on:
  pull_request:
    paths: ['mlg.bib']

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install -g bibtex-tidy

      - name: Run BibTex Tidy and save to temp file
        run: bibtex-tidy --curly --tab --align=13 --sort=key --duplicates=key --no-escape --sort-fields=cat,title,shorttitle,author,year,month,day,journal,booktitle,location,on,publisher,address,series,volume,number,pages,doi,isbn,issn,url,urldate,copyright,note,metadata --no-tidy-comments --no-remove-dupe-fields --no-lowercase --wrap=80 mlg.bib

      - uses: getsentry/action-git-diff-suggestions@main
        with:
          message: 'eslint made the following change'
